name: Deploy WantToSing to GitHub Pages

on:
  workflow_dispatch: # 允許手動觸發工作流程
  # push:
    # branches: [ master, main ] # 確保 main 或 master 分支推送時都會觸發

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x' # 必須與你的 .csproj (net10.0) 匹配

      - name: Publish .NET Core Project
        run: dotnet publish WantToSing.csproj -c Release -o release --nologo

      # 解決 GitHub Pages 不支援 SPA 路由的問題
      - name: Copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # 解決 GitHub Pages 預設忽略底線開頭資料夾（_framework）的問題
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot